#! /bin/sh

xset s off -dpms

sxhkd &
lxpolkit &
~/.config/polybar/launch.sh &
~/.fehbg
~/.config/conky/launch.sh
picom -b -i 0.9

bspc monitor -d web code term chat video

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
